---
language: ruby
bundler_args: --without development system_tests
before_install: rm Gemfile.lock || true
rvm:
  - 2.1.5
  - 2.0.0
  - 1.9.3
  - jruby-19mode
script: bundle exec rake test
env:
  - PUPPET_VERSION="~> 3.7.4" FUTURE_PARSER=yes
  - PUPPET_VERSION="~> 3.7.4" STRICT_VARIABLES=yes FUTURE_PARSER=yes
matrix:
  exclude:
  - rvm: jruby-19mode
    env: PUPPET_VERSION="~> 3.7.4" FUTURE_PARSER=yes
  - rvm: 1.9.3
    env: PUPPET_VERSION="~> 3.7.4" FUTURE_PARSER=yes
  allow_failures:
    - rvm: 1.9.3
